/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class FpgaJsonParser */

#ifndef _Included_FpgaJsonParser
#define _Included_FpgaJsonParser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     FpgaJsonParser
 * Method:    booleanMethod
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_FpgaJsonParser_booleanMethod
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     FpgaJsonParser
 * Method:    parseJson
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_FpgaJsonParser_parseJson
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
